version: '3.8'

services:
  news-digest:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      # Load from .env file - no hardcoded keys!
      - SENDER_EMAIL=${SENDER_EMAIL}
      - SENDER_PASSWORD=${SENDER_PASSWORD}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - GROK_API_KEY=${GROK_API_KEY}
      - ADMIN_API_KEY=${ADMIN_API_KEY}
      - UNSUBSCRIBE_SECRET=${UNSUBSCRIBE_SECRET}
      - DATABASE_URL=sqlite:///./data/news_digest.db
      - BASE_URL=${BASE_URL:-http://localhost:8000}
      - SMTP_SERVER=${SMTP_SERVER:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PRODUCTION=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Add a database service for production
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: news_digest
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:

# Optional: Nginx reverse proxy for production
nginx:
  image: nginx:alpine
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./ssl:/etc/nginx/ssl  # For SSL certificates
  depends_on:
    - news-digest
  restart: unless-stopped
  profiles:
    - production 